"""Create the two deploy service principals and assign them to the workspace.

Run once during initial workspace bootstrap. Idempotent — running again with
existing SPs prints their IDs without creating duplicates.

This is a *prerequisite* operation for the `_platform` bundle. It runs at the
ACCOUNT level, not the workspace level, and requires Databricks account admin
or workspace admin privileges (specifically, the ability to manage service
principals in the account console).

Run from a machine authenticated to the Databricks account, not a workspace:

    databricks auth login --host https://accounts.cloud.databricks.com \\
        --account-id 020f2275-adfe-44a9-99fa-e65e9369cea9

    python scripts/setup/create_service_principals.py \\
        --account-id 020f2275-adfe-44a9-99fa-e65e9369cea9 \\
        --workspace-id <numeric-workspace-id>

Output: the script prints the SP application IDs (UUIDs). **Copy these down**
— they're needed to configure OIDC federation policies in the next step.
"""

from __future__ import annotations

import argparse
import sys

from databricks.sdk import AccountClient
from databricks.sdk.service import iam


# Service principals to create. Display name is the human-readable name shown
# in the account console; application ID is generated by Databricks and is
# what OIDC federation policies bind to.
SP_DISPLAY_NAMES = ["ecdh-deploy-dev", "ecdh-deploy-prod"]


def find_existing(account: AccountClient, display_name: str) -> iam.ServicePrincipal | None:
    """Return the existing SP with the given display name, or None."""
    for sp in account.service_principals.list(filter=f'displayName eq "{display_name}"'):
        return sp
    return None


def create_or_get(account: AccountClient, display_name: str) -> iam.ServicePrincipal:
    """Create the SP if it doesn't exist; return the existing one if it does."""
    existing = find_existing(account, display_name)
    if existing is not None:
        print(
            f"  exists  display_name={display_name}  "
            f"id={existing.id}  application_id={existing.application_id}"
        )
        return existing

    sp = account.service_principals.create(
        display_name=display_name,
        active=True,
    )
    print(
        f"  created display_name={display_name}  "
        f"id={sp.id}  application_id={sp.application_id}"
    )
    return sp


def assign_to_workspace(
    account: AccountClient,
    workspace_id: int,
    sp: iam.ServicePrincipal,
) -> None:
    """Grant the SP workspace access at USER level.

    USER is sufficient for deploys — the SP doesn't need workspace admin. The
    catalog-level grants applied separately (see grant_catalog_permissions.sql)
    give it the specific UC permissions it needs.
    """
    account.workspace_assignment.update(
        workspace_id=workspace_id,
        principal_id=int(sp.id),
        permissions=[iam.WorkspacePermission.USER],
    )
    print(f"  assigned to workspace {workspace_id} (USER permission)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--account-id",
        required=True,
        help="Databricks account ID (UUID).",
    )
    parser.add_argument(
        "--workspace-id",
        required=True,
        type=int,
        help=(
            "Numeric workspace ID to assign the SPs to. Find with "
            "`databricks workspaces list` against the account."
        ),
    )
    args = parser.parse_args()

    # AccountClient reads account-level auth from the environment. The auth
    # configured via `databricks auth login --host https://accounts.cloud.databricks.com`
    # is what gets used.
    account = AccountClient(account_id=args.account_id)

    print(f"Creating service principals in account {args.account_id}")
    print(f"Assigning to workspace {args.workspace_id}\n")

    sps: list[iam.ServicePrincipal] = []
    for name in SP_DISPLAY_NAMES:
        sp = create_or_get(account, name)
        assign_to_workspace(account, args.workspace_id, sp)
        sps.append(sp)
        print()

    print("=" * 70)
    print("CAPTURE BOTH IDs FOR EACH SP — they get used in different places:")
    print("=" * 70)
    for sp in sps:
        print(f"  {sp.display_name}")
        print(f"    id (numeric)        : {sp.id}")
        print(f"      ^ Use as the argument to scripts/setup/create_federation_policies.sh")
        print(f"        and to `databricks account service-principal-federation-policy create`.")
        print(f"        This is the SP's internal record id — the 'primary key'.")
        print()
        print(f"    application_id (UUID): {sp.application_id}")
        print(f"      ^ Use as DATABRICKS_CLIENT_ID in GitHub Actions workflows,")
        print(f"        and stored as a GitHub Environment variable per env.")
        print(f"        This is the SP's OAuth client identifier.")
        print()

    print("Next steps:")
    print("  1. For each SP, create an OIDC federation policy using the *numeric id*:")
    print("       bash scripts/setup/create_federation_policies.sh dev <DEV-SP-NUMERIC-ID>")
    print("       bash scripts/setup/create_federation_policies.sh prod <PROD-SP-NUMERIC-ID>")
    print()
    print("  2. In the GitHub repo settings, create environments `dev` and `prod`,")
    print("     and add a Variable `DATABRICKS_CLIENT_ID` to each, set to the")
    print("     corresponding SP's *application_id* UUID.")
    print()
    print("  3. Once catalogs exist, run scripts/setup/grant_catalog_permissions.sql")
    print("     to apply USE_CATALOG and CREATE_SCHEMA grants.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
